name = "IntroMathMethods"
uuid = "5a20ada7-fe87-4287-9b8b-c63809322aa7"
authors = ["Dale Black <djblack@uci.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
